services:
  - type: web
    plan: free
    name: cloudtp3
    runtime: node
    branch: main
    repo: https://github.com/DVMkhpte/cloud_blueprint_1
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
            name: cloudtp3__db
            property: connectionString

databases:
  - name: cloudtp3__db
    plan: free
